server:
  port: 8081
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gz?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .html

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: demo.model
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true