package demo.model;

import java.util.ArrayList;
import java.util.List;

public class DxyareaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public DxyareaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNull() {
            addCriterion("province_name is null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNotNull() {
            addCriterion("province_name is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameEqualTo(String value) {
            addCriterion("province_name =", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotEqualTo(String value) {
            addCriterion("province_name <>", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThan(String value) {
            addCriterion("province_name >", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThanOrEqualTo(String value) {
            addCriterion("province_name >=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThan(String value) {
            addCriterion("province_name <", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThanOrEqualTo(String value) {
            addCriterion("province_name <=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLike(String value) {
            addCriterion("province_name like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotLike(String value) {
            addCriterion("province_name not like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIn(List<String> values) {
            addCriterion("province_name in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotIn(List<String> values) {
            addCriterion("province_name not in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameBetween(String value1, String value2) {
            addCriterion("province_name between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotBetween(String value1, String value2) {
            addCriterion("province_name not between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameIsNull() {
            addCriterion("province_englishname is null");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameIsNotNull() {
            addCriterion("province_englishname is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameEqualTo(String value) {
            addCriterion("province_englishname =", value, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameNotEqualTo(String value) {
            addCriterion("province_englishname <>", value, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameGreaterThan(String value) {
            addCriterion("province_englishname >", value, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameGreaterThanOrEqualTo(String value) {
            addCriterion("province_englishname >=", value, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameLessThan(String value) {
            addCriterion("province_englishname <", value, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameLessThanOrEqualTo(String value) {
            addCriterion("province_englishname <=", value, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameLike(String value) {
            addCriterion("province_englishname like", value, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameNotLike(String value) {
            addCriterion("province_englishname not like", value, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameIn(List<String> values) {
            addCriterion("province_englishname in", values, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameNotIn(List<String> values) {
            addCriterion("province_englishname not in", values, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameBetween(String value1, String value2) {
            addCriterion("province_englishname between", value1, value2, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceEnglishnameNotBetween(String value1, String value2) {
            addCriterion("province_englishname not between", value1, value2, "provinceEnglishname");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountIsNull() {
            addCriterion("province_confirmedcount is null");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountIsNotNull() {
            addCriterion("province_confirmedcount is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountEqualTo(String value) {
            addCriterion("province_confirmedcount =", value, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountNotEqualTo(String value) {
            addCriterion("province_confirmedcount <>", value, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountGreaterThan(String value) {
            addCriterion("province_confirmedcount >", value, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountGreaterThanOrEqualTo(String value) {
            addCriterion("province_confirmedcount >=", value, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountLessThan(String value) {
            addCriterion("province_confirmedcount <", value, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountLessThanOrEqualTo(String value) {
            addCriterion("province_confirmedcount <=", value, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountLike(String value) {
            addCriterion("province_confirmedcount like", value, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountNotLike(String value) {
            addCriterion("province_confirmedcount not like", value, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountIn(List<String> values) {
            addCriterion("province_confirmedcount in", values, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountNotIn(List<String> values) {
            addCriterion("province_confirmedcount not in", values, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountBetween(String value1, String value2) {
            addCriterion("province_confirmedcount between", value1, value2, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceConfirmedcountNotBetween(String value1, String value2) {
            addCriterion("province_confirmedcount not between", value1, value2, "provinceConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountIsNull() {
            addCriterion("province_suspectedcount is null");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountIsNotNull() {
            addCriterion("province_suspectedcount is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountEqualTo(String value) {
            addCriterion("province_suspectedcount =", value, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountNotEqualTo(String value) {
            addCriterion("province_suspectedcount <>", value, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountGreaterThan(String value) {
            addCriterion("province_suspectedcount >", value, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountGreaterThanOrEqualTo(String value) {
            addCriterion("province_suspectedcount >=", value, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountLessThan(String value) {
            addCriterion("province_suspectedcount <", value, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountLessThanOrEqualTo(String value) {
            addCriterion("province_suspectedcount <=", value, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountLike(String value) {
            addCriterion("province_suspectedcount like", value, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountNotLike(String value) {
            addCriterion("province_suspectedcount not like", value, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountIn(List<String> values) {
            addCriterion("province_suspectedcount in", values, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountNotIn(List<String> values) {
            addCriterion("province_suspectedcount not in", values, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountBetween(String value1, String value2) {
            addCriterion("province_suspectedcount between", value1, value2, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceSuspectedcountNotBetween(String value1, String value2) {
            addCriterion("province_suspectedcount not between", value1, value2, "provinceSuspectedcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountIsNull() {
            addCriterion("province_curedcount is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountIsNotNull() {
            addCriterion("province_curedcount is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountEqualTo(String value) {
            addCriterion("province_curedcount =", value, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountNotEqualTo(String value) {
            addCriterion("province_curedcount <>", value, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountGreaterThan(String value) {
            addCriterion("province_curedcount >", value, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountGreaterThanOrEqualTo(String value) {
            addCriterion("province_curedcount >=", value, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountLessThan(String value) {
            addCriterion("province_curedcount <", value, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountLessThanOrEqualTo(String value) {
            addCriterion("province_curedcount <=", value, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountLike(String value) {
            addCriterion("province_curedcount like", value, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountNotLike(String value) {
            addCriterion("province_curedcount not like", value, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountIn(List<String> values) {
            addCriterion("province_curedcount in", values, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountNotIn(List<String> values) {
            addCriterion("province_curedcount not in", values, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountBetween(String value1, String value2) {
            addCriterion("province_curedcount between", value1, value2, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceCuredcountNotBetween(String value1, String value2) {
            addCriterion("province_curedcount not between", value1, value2, "provinceCuredcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountIsNull() {
            addCriterion("province_deadcount is null");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountIsNotNull() {
            addCriterion("province_deadcount is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountEqualTo(String value) {
            addCriterion("province_deadcount =", value, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountNotEqualTo(String value) {
            addCriterion("province_deadcount <>", value, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountGreaterThan(String value) {
            addCriterion("province_deadcount >", value, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountGreaterThanOrEqualTo(String value) {
            addCriterion("province_deadcount >=", value, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountLessThan(String value) {
            addCriterion("province_deadcount <", value, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountLessThanOrEqualTo(String value) {
            addCriterion("province_deadcount <=", value, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountLike(String value) {
            addCriterion("province_deadcount like", value, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountNotLike(String value) {
            addCriterion("province_deadcount not like", value, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountIn(List<String> values) {
            addCriterion("province_deadcount in", values, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountNotIn(List<String> values) {
            addCriterion("province_deadcount not in", values, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountBetween(String value1, String value2) {
            addCriterion("province_deadcount between", value1, value2, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceDeadcountNotBetween(String value1, String value2) {
            addCriterion("province_deadcount not between", value1, value2, "provinceDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountIsNull() {
            addCriterion("city_confirmedcount is null");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountIsNotNull() {
            addCriterion("city_confirmedcount is not null");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountEqualTo(String value) {
            addCriterion("city_confirmedcount =", value, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountNotEqualTo(String value) {
            addCriterion("city_confirmedcount <>", value, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountGreaterThan(String value) {
            addCriterion("city_confirmedcount >", value, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountGreaterThanOrEqualTo(String value) {
            addCriterion("city_confirmedcount >=", value, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountLessThan(String value) {
            addCriterion("city_confirmedcount <", value, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountLessThanOrEqualTo(String value) {
            addCriterion("city_confirmedcount <=", value, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountLike(String value) {
            addCriterion("city_confirmedcount like", value, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountNotLike(String value) {
            addCriterion("city_confirmedcount not like", value, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountIn(List<String> values) {
            addCriterion("city_confirmedcount in", values, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountNotIn(List<String> values) {
            addCriterion("city_confirmedcount not in", values, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountBetween(String value1, String value2) {
            addCriterion("city_confirmedcount between", value1, value2, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityConfirmedcountNotBetween(String value1, String value2) {
            addCriterion("city_confirmedcount not between", value1, value2, "cityConfirmedcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountIsNull() {
            addCriterion("city_curedcount is null");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountIsNotNull() {
            addCriterion("city_curedcount is not null");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountEqualTo(String value) {
            addCriterion("city_curedcount =", value, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountNotEqualTo(String value) {
            addCriterion("city_curedcount <>", value, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountGreaterThan(String value) {
            addCriterion("city_curedcount >", value, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountGreaterThanOrEqualTo(String value) {
            addCriterion("city_curedcount >=", value, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountLessThan(String value) {
            addCriterion("city_curedcount <", value, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountLessThanOrEqualTo(String value) {
            addCriterion("city_curedcount <=", value, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountLike(String value) {
            addCriterion("city_curedcount like", value, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountNotLike(String value) {
            addCriterion("city_curedcount not like", value, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountIn(List<String> values) {
            addCriterion("city_curedcount in", values, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountNotIn(List<String> values) {
            addCriterion("city_curedcount not in", values, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountBetween(String value1, String value2) {
            addCriterion("city_curedcount between", value1, value2, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityCuredcountNotBetween(String value1, String value2) {
            addCriterion("city_curedcount not between", value1, value2, "cityCuredcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountIsNull() {
            addCriterion("city_deadcount is null");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountIsNotNull() {
            addCriterion("city_deadcount is not null");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountEqualTo(String value) {
            addCriterion("city_deadcount =", value, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountNotEqualTo(String value) {
            addCriterion("city_deadcount <>", value, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountGreaterThan(String value) {
            addCriterion("city_deadcount >", value, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountGreaterThanOrEqualTo(String value) {
            addCriterion("city_deadcount >=", value, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountLessThan(String value) {
            addCriterion("city_deadcount <", value, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountLessThanOrEqualTo(String value) {
            addCriterion("city_deadcount <=", value, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountLike(String value) {
            addCriterion("city_deadcount like", value, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountNotLike(String value) {
            addCriterion("city_deadcount not like", value, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountIn(List<String> values) {
            addCriterion("city_deadcount in", values, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountNotIn(List<String> values) {
            addCriterion("city_deadcount not in", values, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountBetween(String value1, String value2) {
            addCriterion("city_deadcount between", value1, value2, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andCityDeadcountNotBetween(String value1, String value2) {
            addCriterion("city_deadcount not between", value1, value2, "cityDeadcount");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeIsNull() {
            addCriterion("province_zipcode is null");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeIsNotNull() {
            addCriterion("province_zipcode is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeEqualTo(String value) {
            addCriterion("province_zipcode =", value, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeNotEqualTo(String value) {
            addCriterion("province_zipcode <>", value, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeGreaterThan(String value) {
            addCriterion("province_zipcode >", value, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("province_zipcode >=", value, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeLessThan(String value) {
            addCriterion("province_zipcode <", value, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeLessThanOrEqualTo(String value) {
            addCriterion("province_zipcode <=", value, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeLike(String value) {
            addCriterion("province_zipcode like", value, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeNotLike(String value) {
            addCriterion("province_zipcode not like", value, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeIn(List<String> values) {
            addCriterion("province_zipcode in", values, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeNotIn(List<String> values) {
            addCriterion("province_zipcode not in", values, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeBetween(String value1, String value2) {
            addCriterion("province_zipcode between", value1, value2, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andProvinceZipcodeNotBetween(String value1, String value2) {
            addCriterion("province_zipcode not between", value1, value2, "provinceZipcode");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("city_name is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("city_name is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("city_name =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("city_name <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("city_name >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("city_name >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("city_name <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("city_name <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("city_name like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("city_name not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("city_name in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("city_name not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("city_name between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("city_name not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameIsNull() {
            addCriterion("city_englishname is null");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameIsNotNull() {
            addCriterion("city_englishname is not null");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameEqualTo(String value) {
            addCriterion("city_englishname =", value, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameNotEqualTo(String value) {
            addCriterion("city_englishname <>", value, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameGreaterThan(String value) {
            addCriterion("city_englishname >", value, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameGreaterThanOrEqualTo(String value) {
            addCriterion("city_englishname >=", value, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameLessThan(String value) {
            addCriterion("city_englishname <", value, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameLessThanOrEqualTo(String value) {
            addCriterion("city_englishname <=", value, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameLike(String value) {
            addCriterion("city_englishname like", value, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameNotLike(String value) {
            addCriterion("city_englishname not like", value, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameIn(List<String> values) {
            addCriterion("city_englishname in", values, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameNotIn(List<String> values) {
            addCriterion("city_englishname not in", values, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameBetween(String value1, String value2) {
            addCriterion("city_englishname between", value1, value2, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityEnglishnameNotBetween(String value1, String value2) {
            addCriterion("city_englishname not between", value1, value2, "cityEnglishname");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeIsNull() {
            addCriterion("city_zipcode is null");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeIsNotNull() {
            addCriterion("city_zipcode is not null");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeEqualTo(String value) {
            addCriterion("city_zipcode =", value, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeNotEqualTo(String value) {
            addCriterion("city_zipcode <>", value, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeGreaterThan(String value) {
            addCriterion("city_zipcode >", value, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("city_zipcode >=", value, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeLessThan(String value) {
            addCriterion("city_zipcode <", value, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeLessThanOrEqualTo(String value) {
            addCriterion("city_zipcode <=", value, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeLike(String value) {
            addCriterion("city_zipcode like", value, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeNotLike(String value) {
            addCriterion("city_zipcode not like", value, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeIn(List<String> values) {
            addCriterion("city_zipcode in", values, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeNotIn(List<String> values) {
            addCriterion("city_zipcode not in", values, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeBetween(String value1, String value2) {
            addCriterion("city_zipcode between", value1, value2, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCityZipcodeNotBetween(String value1, String value2) {
            addCriterion("city_zipcode not between", value1, value2, "cityZipcode");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountIsNull() {
            addCriterion("city_suspectedcount is null");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountIsNotNull() {
            addCriterion("city_suspectedcount is not null");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountEqualTo(String value) {
            addCriterion("city_suspectedcount =", value, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountNotEqualTo(String value) {
            addCriterion("city_suspectedcount <>", value, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountGreaterThan(String value) {
            addCriterion("city_suspectedcount >", value, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountGreaterThanOrEqualTo(String value) {
            addCriterion("city_suspectedcount >=", value, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountLessThan(String value) {
            addCriterion("city_suspectedcount <", value, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountLessThanOrEqualTo(String value) {
            addCriterion("city_suspectedcount <=", value, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountLike(String value) {
            addCriterion("city_suspectedcount like", value, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountNotLike(String value) {
            addCriterion("city_suspectedcount not like", value, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountIn(List<String> values) {
            addCriterion("city_suspectedcount in", values, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountNotIn(List<String> values) {
            addCriterion("city_suspectedcount not in", values, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountBetween(String value1, String value2) {
            addCriterion("city_suspectedcount between", value1, value2, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andCitySuspectedcountNotBetween(String value1, String value2) {
            addCriterion("city_suspectedcount not between", value1, value2, "citySuspectedcount");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dxyarea
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 18 11:28:45 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dxyarea
     *
     * @mbggenerated Wed Mar 18 11:28:45 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}